name: Analyze Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable

      - name: Run SwiftLint
        run: |
          /usr/local/bin/swiftlint lint

      - name: Build and Analyze
        run: >
          xcodebuild clean build analyze
          -project "Mochi Diffusion.xcodeproj"
          -scheme "Mochi Diffusion"
          CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}
