name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable

      - name: Build and Analyze
        run: >
          xcodebuild clean build analyze
          -exportLocalizations
          -project "Mochi Diffusion.xcodeproj"
          -scheme "Mochi Diffusion"
          -localizationPath "./locale"
          -exportLanguage en
          CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload source locale artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: en-source-locale
          path: './locale/en.xcloc/Localized Contents/en.xliff'

  crowdin:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: en-source-locale
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload source to Crowdin
        uses: crowdin/github-action@v2.2.0
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false

          source: en.xliff
          translation: '%osx_locale%.xliff'

          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
